In [1]:
#numpy library installation
!pip install numpy

In [2]:
#importing the library
import numpy as np

In [3]:
#library version
np.__version__

'1.22.4'

In [4]:
array1 = np.array(11,12,13,14,15)
array1

TypeError: ignored

In [5]:
array1 = np.array([11,12,13,14,15])
array1
#print(array1)

array([11, 12, 13, 14, 15])

In [6]:
array2 = np.array([1,2,3],[4,5,6],[7,8,9])
array2

TypeError: ignored

In [ ]:
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2

# datatype

In [7]:
array3 = np.array([10,11,12,14])
print(array3)
print(array3.dtype)

[10 11 12 14]
int64


In [8]:
array4 = np.array([10.0,11.3,12.0,14.8])
print(array4)
print(array4.dtype)

[10.  11.3 12.  14.8]
float64


In [9]:
#check for homogeneous - array
array5 = np.array([10,11,12.0,14.8])
array5

array([10. , 11. , 12. , 14.8])

In [10]:
#heterogenous - not possible
array6 = np.array([10,11,12.0,14.8, 'hello'])
array6

array(['10', '11', '12.0', '14.8', 'hello'], dtype='<U32')

In [11]:
#list vs array
array7 = np.arange(20)
array7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
from timeit import default_timer as timer
array8 = np.random.randn(10000)
array9 = np.random.randn(10000)

In [13]:
lista = list(array8)   #converts to list from array format
listb = list(array9)

sample = 10000

def dot1():
  dot =0
  for i in range(len(lista)):
    dot += lista[i] * listb[i]
  return dot

def dot2():
  return np.dot(array8, array9)

start =timer()
for t in range(sample):
  dot1()
end =timer()
t1 = end -start

start =timer()
for t in range(sample):
  dot2()
end =timer()
t2 = end -start

print('computtaion time for list', t1)
print('computtaion time for array', t2)
print('diff', t1/t2)


computtaion time for list 21.178696637
computtaion time for array 0.03710586299999363
diff 570.7641575942765


In [14]:
#numpy methods / functions
#just for the reference =
array7 = np.arange(20)
array9 = array7
array9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
#copying the elements / arrays from one variable to other
array10 = array7.copy()
array10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
array11 = np.arange(5)
array11

array([0, 1, 2, 3, 4])

In [17]:
array12 = np.arange(10,30,2)
array12

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [18]:
array13 = np.arange(-10,30,2)
array13

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10,  12,  14,
        16,  18,  20,  22,  24,  26,  28])

In [19]:
array13 = np.arange(-10,30,2.5)
array13

array([-10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5,  10. ,
        12.5,  15. ,  17.5,  20. ,  22.5,  25. ,  27.5])

In [20]:
#memory
print(array13.nbytes)

128


In [21]:
#dimentionality
print(array13.ndim)

1


In [22]:
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array2.ndim)

2


In [23]:
#shape
print(array2.shape)

(3, 3)


In [24]:
#itemsize
print(array2.itemsize)

8


In [25]:
#size
print(array2.size)

9


#Indexing

In [26]:
array_1 = np.arange(20,40)
array_1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [27]:
print(array_1[2])

22


In [28]:
print(array_1[7])

27


In [29]:
print(array_1[5:7])

[25 26]


In [30]:
print(array_1[-1])

39


In [31]:
print(array_1[-1:4])

[]


In [32]:
print(array_1[4:-5])

[24 25 26 27 28 29 30 31 32 33 34]


In [33]:
array_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
print(array_2[0])

[1 2 3]


In [35]:
print(array_2[1,1])

5


In [36]:
print(array_2[-1])

[7 8 9]


In [37]:
print(array_2[1][1])

5


In [38]:
print(array_2[0,1])

2


In [39]:
print(array_2[0,1:-1])

[2]


In [40]:
print(array_2[0,1:-2])

[]


In [41]:
print(array_2[:,1])

[2 5 8]


In [42]:
print(array_2[1,:])

[4 5 6]


In [43]:
print(array_2[1:3,:])

[[4 5 6]
 [7 8 9]]


In [44]:
print(array_2[1:2,:])

[[4 5 6]]


#Slicing

In [45]:
array_1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [46]:
array_1[:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [47]:
array_1[1:5]

array([21, 22, 23, 24])

In [48]:
array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
array_2[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
array_2[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [51]:
array_2[2,2]

9

In [52]:
array_2[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [53]:
array_2[:2,:2]

array([[1, 2],
       [4, 5]])

#Basic math operation

In [54]:
array_3 = np.array([1,2,2,3,4,5,5,6])
array_4 = np.array([1,2,2,3,4,5,5,6])
array_3 + array_4

array([ 2,  4,  4,  6,  8, 10, 10, 12])

In [55]:
array_3 - array_4

array([0, 0, 0, 0, 0, 0, 0, 0])

In [56]:
array_3 * array_4

array([ 1,  4,  4,  9, 16, 25, 25, 36])

In [57]:
compare_ = array_3 > 2
print(compare_)

[False False False  True  True  True  True  True]


In [58]:
np.add(array_3, array_4)

array([ 2,  4,  4,  6,  8, 10, 10, 12])

In [59]:
np.subtract(array_3, array_4)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
np.multiply(array_3, array_4)

array([ 1,  4,  4,  9, 16, 25, 25, 36])

In [61]:
np.negative(array_3)

array([-1, -2, -2, -3, -4, -5, -5, -6])

In [62]:
np.concatenate([array_3, array_4])

array([1, 2, 2, 3, 4, 5, 5, 6, 1, 2, 2, 3, 4, 5, 5, 6])

In [63]:
np.concatenate((array_2, array_2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
np.concatenate((array_2, array_2), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
np.concatenate((array_2, array_2), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [66]:
np.concatenate((array_2, array_2), axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
array_2 = np.array([[11,2,34],[4,55,6],[7,8,9]])
deter = np.linalg.det(array_2)
print(deter)

-7072.999999999999


In [69]:
np.diag(array_2) #diagnol matrix

array([11, 55,  9])

In [70]:
evalue, evect = np.linalg.eig(array_2) #eigen value, eigen vector

In [71]:
print(evalue)

[-5.31169138 23.39574353 56.91594785]


In [72]:
print(evect)

[[ 0.90186732 -0.9202832  -0.18098572]
 [-0.01686849  0.18220794 -0.96542252]
 [-0.43168366 -0.3462356  -0.18762605]]


In [73]:
np.linalg.inv(array_2) #inverse matrix

array([[-0.06319808, -0.03591121,  0.2626891 ],
       [-0.0008483 ,  0.0196522 , -0.00989679],
       [ 0.0499081 ,  0.01046232, -0.08440549]])

In [75]:
#Broadcasting
import numpy as np

# Create two arrays
a = np.array([1, 2, 3])  # Shape: (3,)
b = np.array([[4], [5], [6]])  # Shape: (3, 1)

# Perform element-wise addition
c = a + b

print(c)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [79]:
d = np.array([1, 2, 3,4, 5]) #(5,)
e = np.array([[3,4,5,6,8],[5,6,7,9,9],[5,5,5,4,7]]) #(5,)
f = d + e
print(f)

[[ 4  6  8 10 13]
 [ 6  8 10 13 14]
 [ 6  7  8  8 12]]


In [80]:
#linear equation
#x1+x2=2200
#1.5x1 + 4x2 = 5050
a = np.array([[1,1], [1.5,4]])
b = np.array([2200, 5050])
x = np.linalg.solve(a,b)
print(x)

[1500.  700.]


In [81]:
rm1 = np.random.rand()
print(rm1)

0.5680742431743369


In [82]:
rm1 = np.random.rand(5)
print(rm1)

[0.45621635 0.04445103 0.06541771 0.88293215 0.28976899]


In [83]:
rm1 = np.random.rand(5,3,3)
print(rm1)

[[[0.22789204 0.80756369 0.60964782]
  [0.81280944 0.65538635 0.35619063]
  [0.7231168  0.79449743 0.99046104]]

 [[0.99801041 0.98356564 0.83631111]
  [0.90055035 0.60911181 0.49891349]
  [0.36698289 0.69984095 0.26733587]]

 [[0.66919459 0.17448403 0.53368756]
  [0.05346522 0.70101359 0.65549501]
  [0.86810537 0.76649741 0.52450878]]

 [[0.98001278 0.96888279 0.88747043]
  [0.9671841  0.9537837  0.99269344]
  [0.15486516 0.94006968 0.04256157]]

 [[0.59537154 0.87206634 0.12778768]
  [0.2698825  0.45540742 0.63878253]
  [0.81457149 0.49674811 0.75708089]]]


In [85]:
rm2 = np.random.randn()
print(rm2)

-0.8820702317070558


In [87]:
rm2 = np.random.randint(5)
print(rm2)

3


In [88]:
#statiscs
np.sqrt(25)

5.0

In [89]:
np.abs(-15)

15

In [90]:
np.log(10)

2.302585092994046

In [91]:
np.power(4,5)

1024

In [92]:
array_1 = np.array([[1,3,5,7,9],[2,4,6,8,10],[1,2,4,5,6]])
print(array_1)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]
 [ 1  2  4  5  6]]


In [93]:
print('reshaping array1', array_1.reshape(1,-1))

reshaping array1 [[ 1  3  5  7  9  2  4  6  8 10  1  2  4  5  6]]


In [94]:
print('reshaping array1', array_1.reshape(-1,1))

reshaping array1 [[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [ 1]
 [ 2]
 [ 4]
 [ 5]
 [ 6]]


In [95]:
s1 = np.random.randint(10, size=(3,2))
s2 = np.random.randint(10, size=(3,2))
print(s1)
print(s2)

[[5 6]
 [1 0]
 [8 3]]
[[4 6]
 [4 5]
 [9 4]]


In [96]:
np.hstack((s1,s2))

array([[5, 6, 4, 6],
       [1, 0, 4, 5],
       [8, 3, 9, 4]])

In [97]:
np.vstack((s1,s2))

array([[5, 6],
       [1, 0],
       [8, 3],
       [4, 6],
       [4, 5],
       [9, 4]])

In [98]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [99]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [100]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])